const VN_ADDRESS = [
  {
    "name": "Hà Nội",
    "wards": [
      "Minh Châu",
      "Ngọc Hồi",
      "Tây Mỗ",
      "Phú Diễn",
      "Tây Tựu",
      "Thượng Cát",
      "Xuân Đỉnh",
      "Xuân Phương",
      "Đại Xuyên",
      "Phương Liệt",
      "Tùng Thiện",
      "Đoài Phương",
      "Gia Lâm",
      "Suối Hai",
      "Ba Vì",
      "Cổ Đô",
      "Hoàng Liệt",
      "Lĩnh Nam",
      "Tương Mai",
      "Thanh Liệt",
      "Đại Thanh",
      "Thường Tín",
      "Ô Diên",
      "Quảng Bị",
      "Trần Phú",
      "Liên Minh",
      "Thư Lâm",
      "Đông Anh",
      "Phú Xuyên",
      "Quảng Oai",
      "Dương Hòa",
      "Phúc Thịnh",
      "Vĩnh Thanh",
      "Thiên Lộc",
      "Quang Minh",
      "Hương Sơn",
      "Mê Linh",
      "Tiến Thắng",
      "Yên Lãng",
      "Mỹ Đức",
      "Định Công",
      "Bất Bạt",
      "Vật Lại",
      "Yên Bài",
      "Chương Mỹ",
      "Xuân Mai",
      "Phú Nghĩa",
      "Yên Xuân",
      "Phúc Lợi",
      "Việt Hưng",
      "Hòa Lạc",
      "Thanh Oai",
      "Bình Minh",
      "Dân Hòa",
      "Ba Đình",
      "Giảng Võ",
      "Ngọc Hà",
      "Cầu Giấy",
      "Nghĩa Đô",
      "Phù Đổng",
      "Hoài Đức",
      "An Khánh",
      "Phúc Sơn",
      "Sơn Đồng",
      "Chuyên Mỹ",
      "Vĩnh Tuy",
      "Hồng Hà",
      "Cửa Nam",
      "Yên Nghĩa",
      "Hồng Vân",
      "Vĩnh Hưng",
      "Bồ Đề",
      "Kiều Phú",
      "Phú Cát",
      "Sóc Sơn",
      "Kim Anh",
      "Nội Bài",
      "Trung Giã",
      "Quốc Oai",
      "Long Biên",
      "Khương Đình",
      "Phú Lương",
      "Dương Nội",
      "Kiến Hưng",
      "Hà Đông",
      "Hai Bà Trưng",
      "Thượng Phúc",
      "Thạch Thất",
      "Hạ Bằng",
      "Nam Phù",
      "Thanh Trì",
      "Đại Mỗ",
      "Vân Đình",
      "Yên Hòa",
      "Ô Chợ Dừa",
      "Kim Liên",
      "Láng",
      "Đống Đa",
      "Văn Miếu-Quốc Tử Giám",
      "Phú Thượng",
      "Hoàng Mai",
      "Từ Liêm",
      "Đông Ngạc",
      "Hòa Phú",
      "Tây Phương",
      "Hòa Xá",
      "Bát Tràng",
      "Thuận An",
      "Bạch Mai",
      "Thanh Xuân",
      "Sơn Tây",
      "Đan Phượng",
      "Chương Dương",
      "Phượng Dực",
      "Ứng Thiên",
      "Hồng Sơn",
      "Hưng Đạo",
      "Tam Hưng",
      "Ứng Hòa",
      "Hát Môn",
      "Phúc Thọ",
      "Đa Phúc",
      "Phúc Lộc",
      "Hoàn Kiếm",
      "Yên Sở",
      "Tây Hồ"
    ]
  },
  {
    "name": "Hồ Chí Minh",
    "wards": [
      "Thạnh An",
      "Xóm Chiếu",
      "Vĩnh Hội",
      "Khánh Hội",
      "Bình Chánh",
      "Vĩnh Lộc",
      "Tân Vĩnh Lộc",
      "An Thới Đông",
      "Bình Khánh",
      "Bàn Cờ",
      "Xuân Hòa",
      "Bình Đông",
      "Phú Thuận",
      "Tân Mỹ",
      "Phú Định",
      "Chánh Hưng",
      "Long Bình",
      "Tăng Nhơn Phú",
      "Bình Tân",
      "Bình Trị Đông",
      "Phú Giáo",
      "Bình Hưng",
      "Thường Tân",
      "Phú Nhuận",
      "Cầu Kiệu",
      "Tân Bình",
      "Phú Thạnh",
      "Tân Định",
      "Cầu Ông Lãnh",
      "Sài Gòn",
      "Bến Thành",
      "Diên Hồng",
      "Hòa Hưng",
      "Bình Thới",
      "Phú Thọ",
      "Bình Phú",
      "Tân Sơn Nhì",
      "Tây Thạnh",
      "Thủ Đức",
      "Hiệp Bình",
      "Linh Xuân",
      "Bình Trưng",
      "An Khánh",
      "Phú An",
      "Thuận Giao",
      "Bình Hòa",
      "Thủ Dầu Một",
      "Lái Thiêu",
      "An Phú",
      "Rạch Dừa",
      "Long Hòa",
      "Minh Thạnh",
      "Tân Tạo",
      "Long Nguyên",
      "Trừ Văn Thố",
      "Bến Cát",
      "Dầu Tiếng",
      "Tân Khánh",
      "Tân Uyên",
      "Phước Hòa",
      "Chánh Hiệp",
      "Thới Hòa",
      "Tây Nam",
      "Thanh An",
      "Tân Nhựt",
      "Dĩ An",
      "Tân Đông Hiệp",
      "Phú Lợi",
      "Đặc Khu Côn Đảo",
      "Long Điền",
      "Bình Hưng Hòa",
      "Nhiêu Lộc",
      "Chợ Quán",
      "An Đông",
      "Chợ Lớn",
      "Bình Tiên",
      "Phú Lâm",
      "Tân Hưng",
      "Tân Thuận",
      "Vườn Lài",
      "Minh Phụng",
      "Hòa Bình",
      "Đông Hưng Thuận",
      "Trung Mỹ Tây",
      "Tân Thới Hiệp",
      "Thới An",
      "An Phú Đông",
      "Gia Định",
      "Bình Thạnh",
      "Bình Lợi Trung",
      "Thạnh Mỹ Tây",
      "Bình Quới",
      "An Lạc",
      "Hạnh Thông",
      "An Nhơn",
      "Gò Vấp",
      "Thông Tây Hội",
      "An Hội Tây",
      "An Hội Đông",
      "Đức Nhuận",
      "Tân Sơn Hòa",
      "Tân Sơn Nhất",
      "Tân Hòa",
      "Bảy Hiền",
      "Bình Lợi",
      "Hưng Long",
      "An Nhơn Tây",
      "Thái Mỹ",
      "Nhuận Đức",
      "Tân An Hội",
      "Củ Chi",
      "Phú Hòa Đông",
      "Bình Mỹ",
      "Cần Giờ",
      "Đông Thạnh",
      "Hóc Môn",
      "Xuân Thới Sơn",
      "Bà Điểm",
      "Nhà Bè",
      "Hiệp Phước",
      "Tam Bình",
      "Phước Long",
      "Long Phước",
      "Long Trường",
      "Cát Lái",
      "Bình Tây",
      "Tân Sơn",
      "Phú Thọ Hòa",
      "Tân Phú",
      "Bàu Bàng",
      "Tam Thắng",
      "Phước Thắng",
      "Bà Rịa",
      "Long Hương",
      "Tam Long",
      "Phú Mỹ",
      "Tân Thành",
      "Tân Phước",
      "Tân Hải",
      "Châu Pha",
      "Ngãi Giao",
      "Bình Giã",
      "Kim Long",
      "Châu Đức",
      "Xuân Sơn",
      "Nghĩa Thành",
      "Hồ Tràm",
      "Xuyên Mộc",
      "Hòa Hội",
      "Bàu Lâm",
      "Đất Đỏ",
      "Long Hải",
      "Phước Hải",
      "Long Sơn",
      "Hòa Hiệp",
      "Bình Châu",
      "Vũng Tàu",
      "Bình Cơ",
      "Bắc Tân Uyên",
      "An Long",
      "Phước Thành",
      "Bình Dương",
      "Tân Hiệp",
      "Hòa Lợi",
      "Chánh Phú Hòa",
      "Vĩnh Tân",
      "Đông Hòa",
      "Thuận An"
    ]
  },
  {
    "name": "Đà Nẵng",
    "wards": [
      "Tam Hải",
      "Núi Thành",
      "Hải Vân",
      "Thạnh Mỹ",
      "Tân Hiệp",
      "Đặc Khu Hoàng Sa",
      "Quảng Phú",
      "Hương Trà",
      "Bàn Thạch",
      "Tây Hồ",
      "Chiên Đàn",
      "Phú Ninh",
      "Lãnh Ngọc",
      "Tiên Phước",
      "Thạnh Bình",
      "Sơn Cẩm Hà",
      "Trà Liên",
      "Trà Giáp",
      "Trà Tân",
      "Trà Đốc",
      "Trà My",
      "Trà Mai",
      "Trà Tập",
      "Trà Vân",
      "Trà Linh",
      "Trà Leng",
      "Thăng Bình",
      "Thăng An",
      "Thăng Trường",
      "Thăng Điền",
      "Thăng Phú",
      "Đồng Dương",
      "Quế Sơn Trung",
      "Quế Sơn",
      "Xuân Phú",
      "Nông Sơn",
      "Quế Phước",
      "Duy Nghĩa",
      "Nam Phước",
      "Duy Xuyên",
      "Thu Bồn",
      "Điện Bàn",
      "Điện Bàn Đông",
      "An Thắng",
      "Điện Bàn Bắc",
      "Điện Bàn Tây",
      "Gò Nổi",
      "Hội An",
      "Hội An Đông",
      "Hội An Tây",
      "Đại Lộc",
      "Hà Nha",
      "Thượng Đức",
      "Vu Gia",
      "Phú Thuận",
      "Bến Giằng",
      "Nam Giang",
      "Đắc Pring",
      "La Dêê",
      "Laêê",
      "Sông Vàng",
      "Sông Kôn",
      "Đông Giang",
      "Bến Hiên",
      "A Vương",
      "Tây Giang",
      "Hùng Sơn",
      "Hiệp Đức",
      "Việt An",
      "Phước Trà",
      "Khâm Đức",
      "Phước Năng",
      "Phước Chánh",
      "Phước Thành",
      "Phước Hiệp",
      "Hải Châu",
      "Hòa Cường",
      "Thanh Khê",
      "An Khê",
      "An Hải",
      "Sơn Trà",
      "Ngũ Hành Sơn",
      "Hòa Khánh",
      "Liên Chiểu",
      "Cẩm Lệ",
      "Hòa Xuân",
      "Hòa Vang",
      "Hòa Tiến",
      "Bà Nà",
      "Tam Mỹ",
      "Tam Anh",
      "Đức Phú",
      "Tam Xuân",
      "Tam Kỳ"
    ]
  },
  {
    "name": "Hải Phòng",
    "wards": [
      "Mao Điền",
      "Việt Hòa",
      "Cẩm Giàng",
      "Tân Hưng",
      "Ái Quốc",
      "An Khánh",
      "Tân Minh",
      "Hải An",
      "Nam Đồ Sơn",
      "Dương Kinh",
      "Đông Hải",
      "Đường An",
      "Thượng Hồng",
      "Bình Giang",
      "Gia Phúc",
      "An Lão",
      "Kiến Hải",
      "Kiến An",
      "Phù Liễn",
      "An Biên",
      "Quyết Thắng",
      "Tiên Minh",
      "Trần Liễu",
      "Lê Thanh Nghị",
      "Thạch Khôi",
      "Tân Kỳ",
      "Nguyên Giáp",
      "Nam An Phụ",
      "Bắc An Phụ",
      "Hà Nam",
      "Hà Tây",
      "Nguyễn Lương Bằng",
      "Lạc Phượng",
      "Trần Nhân Tông",
      "Trần Hưng Đạo",
      "Đại Sơn",
      "Đặc Khu Bạch Long Vĩ",
      "An Hải",
      "Kiến Hưng",
      "Gia Viên",
      "Vĩnh Am",
      "Trường Tân",
      "Hồng An",
      "An Phong",
      "Kim Thành",
      "Thiên Hương",
      "Lưu Kiếm",
      "Hòa Bình",
      "Nam Triệu",
      "Việt Khê",
      "Lê Ích Mộc",
      "An Phú",
      "Hà Bắc",
      "Lai Khê",
      "An Hưng",
      "An Quang",
      "An Trường",
      "Kiến Minh",
      "Nghi Dương",
      "Tiên Lãng",
      "Chấn Hưng",
      "Hùng Thắng",
      "Vĩnh Bảo",
      "Nguyễn Bỉnh Khiêm",
      "Vĩnh Hải",
      "Vĩnh Hòa",
      "Vĩnh Thịnh",
      "Vĩnh Thuận",
      "Bạch Đằng",
      "Hải Dương",
      "Thành Đông",
      "Nam Đồng",
      "Chí Linh",
      "Nguyễn Trãi",
      "Lê Đại Hành",
      "Kinh Môn",
      "Nguyễn Đại Năng",
      "Phạm Sư Mạnh",
      "Nhị Chiểu",
      "Nam Sách",
      "Thái Tân",
      "Trần Phú",
      "Hợp Tiến",
      "Thanh Hà",
      "Hà Đông",
      "Cẩm Giang",
      "Tuệ Tĩnh",
      "Tứ Kỳ",
      "Chí Minh",
      "Ninh Giang",
      "Vĩnh Lại",
      "Khúc Thừa Dụ",
      "Tân An",
      "Hồng Châu",
      "Thanh Miện",
      "Bắc Thanh Miện",
      "Hải Hưng",
      "Nam Thanh Miện",
      "An Thành",
      "Đặc Khu Cát Hải",
      "Kiến Thụy",
      "Thủy Nguyên",
      "Hồng Bàng",
      "Ngô Quyền",
      "Lê Chân",
      "Đồ Sơn",
      "Hưng Đạo",
      "An Dương",
      "Tứ Minh",
      "Chu Văn An",
      "Kẻ Sặt",
      "Gia Lộc",
      "Yết Kiêu",
      "Phú Thái"
    ]
  },
  {
    "name": "Cần Thơ",
    "wards": [
      "Phong Nẫm",
      "Lai Hòa",
      "Vĩnh Hải",
      "Mỹ Phước",
      "Thạnh Phú",
      "Thới Hưng",
      "Trường Long",
      "Long Tuyền",
      "Cái Khế",
      "An Bình",
      "Tân Lộc",
      "Ninh Kiều",
      "Tân An",
      "Thới An Đông",
      "Cái Răng",
      "Hưng Phú",
      "Ô Môn",
      "Thới Long",
      "Phước Thới",
      "Trung Nhứt",
      "Phong Điền",
      "Nhơn Ái",
      "Thới Lai",
      "Đông Thuận",
      "Trường Xuân",
      "Trường Thành",
      "Cờ Đỏ",
      "Đông Hiệp",
      "Trung Hưng",
      "Vĩnh Thạnh",
      "Vĩnh Trinh",
      "Thạnh An",
      "Thạnh Quới",
      "Vị Thanh",
      "Vị Tân",
      "Hỏa Lựu",
      "Vị Thủy",
      "Vĩnh Thuận Đông",
      "Vị Thanh 1",
      "Vĩnh Tường",
      "Vĩnh Viễn",
      "Xà Phiên",
      "Lương Tâm",
      "Long Bình",
      "Long Mỹ",
      "Long Phú 1",
      "Thạnh Xuân",
      "Tân Hòa",
      "Trường Long Tây",
      "Châu Thành",
      "Đông Phước",
      "Phú Hữu",
      "Đại Thành",
      "Ngã Bảy",
      "Tân Bình",
      "Hòa An",
      "Phương Bình",
      "Tân Phước Hưng",
      "Hiệp Hưng",
      "Phụng Hiệp",
      "Thạnh Hòa",
      "Bình Thủy",
      "Thốt Nốt",
      "Thuận Hưng",
      "Phú Tâm",
      "An Ninh",
      "Thuận Hòa",
      "Hồ Đắc Kiện",
      "Mỹ Tú",
      "Long Hưng",
      "Mỹ Hương",
      "Vĩnh Phước",
      "Vĩnh Châu",
      "Khánh Hòa",
      "Ngã Năm",
      "Mỹ Quới",
      "Tân Long",
      "Phú Lộc",
      "Vĩnh Lợi",
      "Lâm Tân",
      "Thạnh Thới An",
      "Tài Văn",
      "Liêu Tú",
      "Lịch Hội Thượng",
      "Trần Đề",
      "An Thạnh",
      "Cù Lao Dung",
      "Đại Ngãi",
      "Tân Thạnh",
      "Long Phú",
      "Nhơn Mỹ",
      "Phú Lợi",
      "Sóc Trăng",
      "Mỹ Xuyên",
      "Hòa Tú",
      "Gia Hòa",
      "Nhu Gia",
      "Ngọc Tố",
      "Trường Khánh",
      "An Lạc Thôn",
      "Kế Sách",
      "Thới An Hội",
      "Đại Hải"
    ]
  },
  {
    "name": "Huế",
    "wards": [
      "Dương Nỗ",
      "Phong Điền",
      "Phong Thái",
      "Phong Dinh",
      "Phong Phú",
      "Phong Quảng",
      "Đan Điền",
      "Quảng Điền",
      "Hương Trà",
      "Kim Trà",
      "Bình Điền",
      "Kim Long",
      "Hương An",
      "Phú Xuân",
      "Thuận An",
      "Hóa Châu",
      "Mỹ Thượng",
      "Vỹ Dạ",
      "Thuận Hóa",
      "An Cựu",
      "Thủy Xuân",
      "Phú Vinh",
      "Phú Hồ",
      "Phú Vang",
      "Thanh Thủy",
      "Hương Thủy",
      "Phú Bài",
      "Vinh Lộc",
      "Hưng Lộc",
      "Lộc An",
      "Phú Lộc",
      "Chân Mây-Lăng Cô",
      "Long Quảng",
      "Nam Đông",
      "Khe Tre",
      "A Lưới 1",
      "A Lưới 2",
      "A Lưới 3",
      "A Lưới 4",
      "A Lưới 5"
    ]
  },
  {
    "name": "An Giang",
    "wards": [
      "Hòn Nghệ",
      "Sơn Hải",
      "Hòa Điền",
      "Vĩnh Thông",
      "Vĩnh Tế",
      "Châu Đốc",
      "An Phú",
      "Bình Giang",
      "Bình Sơn",
      "Mỹ Hòa Hưng",
      "Nhơn Hội",
      "Phú Hữu",
      "Tiên Hải",
      "Long Xuyên",
      "Bình Đức",
      "Mỹ Thới",
      "Vĩnh Hậu",
      "Khánh Bình",
      "Tân Châu",
      "Long Phú",
      "Tân An",
      "Châu Phong",
      "Vĩnh Xương",
      "Phú Tân",
      "Phú An",
      "Bình Thạnh Đông",
      "Chợ Vàm",
      "Hòa Lạc",
      "Phú Lâm",
      "Mỹ Đức",
      "Vĩnh Thạnh Trung",
      "Châu Phú",
      "Bình Mỹ",
      "Thạnh Mỹ Tây",
      "Thới Sơn",
      "Tịnh Biên",
      "An Cư",
      "Chi Lăng",
      "Núi Cấm",
      "Ba Chúc",
      "Tri Tôn",
      "Ô Lâm",
      "Cô Tô",
      "Vĩnh Gia",
      "An Châu",
      "Bình Hòa",
      "Cần Đăng",
      "Vĩnh Hanh",
      "Vĩnh An",
      "Cù Lao Giêng",
      "Hội An",
      "Long Điền",
      "Chợ Mới",
      "Nhơn Mỹ",
      "Long Kiến",
      "Thoại Sơn",
      "Óc Eo",
      "Định Mỹ",
      "Phú Hòa",
      "Vĩnh Trạch",
      "Tây Phú",
      "Đặc Khu Thổ Châu",
      "Rạch Giá",
      "Hà Tiên",
      "Tô Châu",
      "Giang Thành",
      "Vĩnh Điều",
      "Hòn Đất",
      "Sơn Kiên",
      "Mỹ Thuận",
      "Thạnh Lộc",
      "Châu Thành",
      "Bình An",
      "Tân Hội",
      "Tân Hiệp",
      "Thạnh Đông",
      "Giồng Riềng",
      "Thạnh Hưng",
      "Long Thạnh",
      "Hòa Hưng",
      "Ngọc Chúc",
      "Hòa Thuận",
      "Định Hòa",
      "Gò Quao",
      "Vĩnh Hòa Hưng",
      "Vĩnh Tuy",
      "Tây Yên",
      "Đông Thái",
      "An Biên",
      "Đông Hòa",
      "Tân Thạnh",
      "Đông Hưng",
      "An Minh",
      "Vân Khánh",
      "Vĩnh Hòa",
      "U Minh Thượng",
      "Vĩnh Bình",
      "Vĩnh Thuận",
      "Vĩnh Phong",
      "Đặc Khu Phú Quốc",
      "Đặc Khu Kiên Hải",
      "Kiên Lương"
    ]
  },
  {
    "name": "Bắc Ninh",
    "wards": [
      "Sa Lý",
      "Biên Sơn",
      "Tuấn Đạo",
      "Kinh Bắc",
      "Võ Cường",
      "Vũ Ninh",
      "Hạp Lĩnh",
      "Nam Sơn",
      "Từ Sơn",
      "Tam Sơn",
      "Đồng Nguyên",
      "Phù Khê",
      "Thuận Thành",
      "Mão Điền",
      "Trạm Lộ",
      "Trí Quả",
      "Song Liễu",
      "Ninh Xá",
      "Quế Võ",
      "Phương Liễu",
      "Nhân Hòa",
      "Đào Viên",
      "Bồng Lai",
      "Chi Lăng",
      "Phù Lãng",
      "Yên Phong",
      "Văn Môn",
      "Tam Giang",
      "Yên Trung",
      "Tam Đa",
      "Tiên Du",
      "Liên Bão",
      "Tân Chi",
      "Đại Đồng",
      "Phật Tích",
      "Gia Bình",
      "Nhân Thắng",
      "Đại Lai",
      "Cao Đức",
      "Đông Cứu",
      "Lương Tài",
      "Lâm Thao",
      "Trung Chính",
      "Trung Kênh",
      "Đồng Kỳ",
      "Đại Sơn",
      "Sơn Động",
      "Tây Yên Tử",
      "Dương Hưu",
      "Yên Định",
      "An Lạc",
      "Vân Sơn",
      "Biển Động",
      "Lục Ngạn",
      "Đèo Gia",
      "Sơn Hải",
      "Tân Sơn",
      "Nam Dương",
      "Kiên Lao",
      "Chũ",
      "Phượng Sơn",
      "Lục Sơn",
      "Trường Sơn",
      "Cẩm Lý",
      "Đông Phú",
      "Nghĩa Phương",
      "Lục Nam",
      "Bắc Lũng",
      "Bảo Đài",
      "Lạng Giang",
      "Mỹ Thái",
      "Kép",
      "Tân Dĩnh",
      "Tiên Lục",
      "Yên Thế",
      "Bố Hạ",
      "Xuân Lương",
      "Tam Tiến",
      "Tân Yên",
      "Ngọc Thiện",
      "Nhã Nam",
      "Phúc Hòa",
      "Quang Trung",
      "Hợp Thịnh",
      "Hiệp Hòa",
      "Hoàng Vân",
      "Xuân Cẩm",
      "Tự Lạn",
      "Việt Yên",
      "Nếnh",
      "Vân Hà",
      "Đồng Việt",
      "Bắc Giang",
      "Đa Mai",
      "Tiền Phong",
      "Tân An",
      "Yên Dũng",
      "Tân Tiến",
      "Cảnh Thụy"
    ]
  },
  {
    "name": "Cà Mau",
    "wards": [
      "U Minh",
      "Tân Hưng",
      "Tạ An Khương",
      "Phan Ngọc Hiển",
      "Đất Mũi",
      "Sông Đốc",
      "Đất Mới",
      "Năm Căn",
      "Đầm Dơi",
      "Cái Nước",
      "Hưng Mỹ",
      "Lương Thế Trân",
      "Phú Mỹ",
      "Hồ Thị Kỷ",
      "Trần Văn Thời",
      "Nguyễn Phích",
      "Khánh An",
      "Khánh Lâm",
      "Lý Văn Lâm",
      "Hòa Thành",
      "Tân Thành",
      "Đá Bạc",
      "Bạc Liêu",
      "Vĩnh Trạch",
      "Hiệp Thành",
      "Giá Rai",
      "Láng Tròn",
      "Phong Thạnh",
      "Hồng Dân",
      "Vĩnh Lộc",
      "Ninh Thạnh Lợi",
      "Ninh Quới",
      "Gành Hào",
      "Định Thành",
      "An Trạch",
      "Long Điền",
      "Đông Hải",
      "Hòa Bình",
      "Vĩnh Mỹ",
      "Vĩnh Hậu",
      "Phước Long",
      "Vĩnh Phước",
      "Phong Hiệp",
      "Vĩnh Thanh",
      "Vĩnh Lợi",
      "Hưng Hội",
      "Châu Thới",
      "An Xuyên",
      "Tân Thuận",
      "Tân Tiến",
      "Trần Phán",
      "Thanh Tùng",
      "Quách Phẩm",
      "Tân Ân",
      "Khánh Bình",
      "Khánh Hưng",
      "Thới Bình",
      "Trí Phải",
      "Tân Lộc",
      "Biển Bạch",
      "Tam Giang",
      "Cái Đôi Vàm",
      "Nguyễn Việt Khái",
      "Phú Tân"
    ]
  },
  {
    "name": "Cao Bằng",
    "wards": [
      "Thục Phán",
      "Tân Giang",
      "Nùng Trí Cao",
      "Sơn Lộ",
      "Hưng Đạo",
      "Bảo Lạc",
      "Cốc Pàng",
      "Cô Ba",
      "Khánh Xuân",
      "Xuân Trường",
      "Huy Giáp",
      "Quảng Lâm",
      "Nam Quang",
      "Lý Bôn",
      "Bảo Lâm",
      "Yên Thổ",
      "Hạ Lang",
      "Lý Quốc",
      "Vinh Quý",
      "Thanh Long",
      "Cần Yên",
      "Thông Nông",
      "Trường Hà",
      "Hà Quảng",
      "Lũng Nặm",
      "Tổng Cọt",
      "Nam Tuấn",
      "Hòa An",
      "Bạch Đằng",
      "Nguyễn Huệ",
      "Ca Thành",
      "Phan Thanh",
      "Thành Công",
      "Tam Kim",
      "Nguyên Bình",
      "Tĩnh Túc",
      "Minh Tâm",
      "Phục Hòa",
      "Bế Văn Đàn",
      "Độc Lập",
      "Quảng Uyên",
      "Hạnh Phúc",
      "Minh Khai",
      "Canh Tân",
      "Kim Đồng",
      "Thạch An",
      "Đông Khê",
      "Đức Long",
      "Quang Hán",
      "Trà Lĩnh",
      "Quang Trung",
      "Đoài Dương",
      "Trùng Khánh",
      "Đàm Thuỷ",
      "Quang Long",
      "Đình Phong"
    ]
  },
  {
    "name": "Đắk Lắk",
    "wards": [
      "Hòa Hiệp",
      "Bình Kiến",
      "Phú Hòa 2",
      "Đức Bình",
      "Ea Bá",
      "Ealy",
      "Phú Yên",
      "Xuân Đài",
      "Dray Bhăng",
      "Buôn Đôn",
      "Ea KTur",
      "Vụ Bổn",
      "Krông Nô",
      "Ea Trang",
      "Ea H'Leo",
      "Ia Lốp",
      "Ia Rvê",
      "Buôn Ma Thuột",
      "Tân An",
      "Tân Lập",
      "Thành Nhất",
      "Ea Kao",
      "Hòa Phú",
      "Buôn Hồ",
      "Cư Bao",
      "Ea Drông",
      "Ea Súp",
      "Ea Rốk",
      "Ea Bung",
      "Ea Wer",
      "Ea Nuôl",
      "Ea Kiết",
      "Ea M'Droh",
      "Quảng Phú",
      "Cuôr Đăng",
      "Cư M'gar",
      "Ea Tul",
      "Pơng Drang",
      "Krông Búk",
      "Cư Pơng",
      "Ea Khăl",
      "Ea Drăng",
      "Ea Wy",
      "Ea Hiao",
      "Krông Năng",
      "Dliê Ya",
      "Tam Giang",
      "Phú Xuân",
      "Krông Pắc",
      "Ea Knuếc",
      "Tân Tiến",
      "Ea Phê",
      "Ea Kly",
      "Ea Kar",
      "Ea Ô",
      "Ea Knốp",
      "Cư Yang",
      "Ea Păl",
      "M'Drắk",
      "Ea Riêng",
      "Cư M'ta",
      "Krông Á",
      "Cư Prao",
      "Hòa Sơn",
      "Dang Kang",
      "Krông Bông",
      "Yang Mao",
      "Cư Pui",
      "Liên Sơn Lắk",
      "Đắk Liêng",
      "Nam Ka",
      "Đắk Phơi",
      "Ea Ning",
      "Krông Ana",
      "Dur Kmăl",
      "Ea Na",
      "Xuân Thọ",
      "Xuân Cảnh",
      "Xuân Lộc",
      "Đông Hòa",
      "Hòa Xuân",
      "Tuy An Bắc",
      "Tuy An Đông",
      "Ô Loan",
      "Tuy An Nam",
      "Tuy An Tây",
      "Hòa Thịnh",
      "Hòa Mỹ",
      "Sơn Thành",
      "Sơn Hòa",
      "Vân Hòa",
      "Tây Sơn",
      "Xuân Lãnh",
      "Phú Mỡ",
      "Xuân Phước",
      "Đồng Xuân",
      "Sông Cầu",
      "Suối Trai",
      "Tuy Hòa",
      "Phú Hòa 1",
      "Tây Hòa",
      "Sông Hinh"
    ]
  },
  {
    "name": "Điện Biên",
    "wards": [
      "Mường Nhé",
      "Sín Thầu",
      "Mường Toong",
      "Nậm Kè",
      "Quảng Lâm",
      "Nà Hỳ",
      "Mường Chà",
      "Nà Bủng",
      "Chà Tở",
      "Si Pa Phìn",
      "Mường Lay",
      "Na Sang",
      "Mường Tùng",
      "Pa Ham",
      "Nậm Nèn",
      "Mường Pồn",
      "Tủa Chùa",
      "Xín Chải",
      "Sính Phình",
      "Tủa Thàng",
      "Sáng Nhè",
      "Tuần Giáo",
      "Quài Tở",
      "Mường Mùn",
      "Pú Nhung",
      "Chiềng Sinh",
      "Mường Ảng",
      "Nà Tấu",
      "Búng Lao",
      "Mường Lạn",
      "Mường Phăng",
      "Điện Biên Phủ",
      "Mường Thanh",
      "Thanh Nưa",
      "Thanh An",
      "Thanh Yên",
      "Sam Mứn",
      "Núa Ngam",
      "Mường Nhà",
      "Na Son",
      "Xa Dung",
      "Pú Nhi",
      "Mường Luân",
      "Tìa Dình",
      "Phình Giàng"
    ]
  },
  {
    "name": "Đồng Nai",
    "wards": [
      "Dak Lua",
      "Phú Lý",
      "Xuân Hòa",
      "Phước Tân",
      "Tam Phước",
      "Đak Ơ",
      "Xuân Đông",
      "Bù Gia Mập",
      "Thanh Sơn",
      "Xuân Lộc",
      "Xuân Thành",
      "Xuân Bắc",
      "La Ngà",
      "Định Quán",
      "Phú Vinh",
      "Phú Hòa",
      "Tà Lài",
      "Nam Cát Tiên",
      "Tân Phú",
      "Phú Lâm",
      "Trị An",
      "Tân An",
      "Tân Triều",
      "Phú Riềng",
      "Nhơn Trạch",
      "Phước An",
      "Phước Thái",
      "Long Phước",
      "Bình An",
      "Long Thành",
      "An Phước",
      "An Viễn",
      "Bình Minh",
      "Trảng Bom",
      "Bàu Hàm",
      "Hưng Thịnh",
      "Dầu Giây",
      "Gia Kiệm",
      "Thống Nhất",
      "Bình Lộc",
      "Bảo Vinh",
      "Xuân Lập",
      "Long Khánh",
      "Hàng Gòn",
      "Xuân Quế",
      "Xuân Đường",
      "Cẩm Mỹ",
      "Sông Ray",
      "Xuân Định",
      "Xuân Phú",
      "Phú Trung",
      "Thuận Lợi",
      "Đồng Tâm",
      "Tân Lợi",
      "Đồng Phú",
      "Phước Sơn",
      "Nghĩa Trung",
      "Bù Đăng",
      "Thọ Sơn",
      "Đak Nhau",
      "Bom Bo",
      "Long Bình",
      "Trảng Dài",
      "Hố Nai",
      "Long Hưng",
      "Đại Phước",
      "Bình Phước",
      "Đồng Xoài",
      "Biên Hòa",
      "Trấn Biên",
      "Tam Hiệp",
      "Phước Bình",
      "Phước Long",
      "Bình Long",
      "An Lộc",
      "Minh Hưng",
      "Chơn Thành",
      "Nha Bích",
      "Tân Quan",
      "Tân Hưng",
      "Tân Khai",
      "Minh Đức",
      "Lộc Thành",
      "Lộc Ninh",
      "Lộc Hưng",
      "Lộc Tấn",
      "Lộc Thạnh",
      "Lộc Quang",
      "Tân Tiến",
      "Thiện Hưng",
      "Hưng Phước",
      "Phú Nghĩa",
      "Đa Kia",
      "Bình Tân",
      "Long Hà"
    ]
  },
  {
    "name": "Đồng Tháp",
    "wards": [
      "Phong Mỹ",
      "Tân Long",
      "Thanh Bình",
      "Tân Thạnh",
      "Long Phú Thuận",
      "Phú Cường",
      "Tân Hồng",
      "Tân Thành",
      "Tân Hộ Cơ",
      "An Phước",
      "An Bình",
      "Hồng Ngự",
      "Thường Lạc",
      "Thường Phước",
      "Long Khánh",
      "An Hòa",
      "Tam Nông",
      "Phú Thọ",
      "Tràm Chim",
      "An Long",
      "Bình Thành",
      "Tháp Mười",
      "Thanh Mỹ",
      "Mỹ Quí",
      "Đốc Binh Kiều",
      "Trường Xuân",
      "Phương Thịnh",
      "Ba Sao",
      "Mỹ Thọ",
      "Bình Hàng Trung",
      "Mỹ Hiệp",
      "Cao Lãnh",
      "Mỹ Ngãi",
      "Mỹ Trà",
      "Mỹ An Hưng",
      "Tân Khánh Trung",
      "Lấp Vò",
      "Lai Vung",
      "Hòa Long",
      "Phong Hòa",
      "Sa Đéc",
      "Tân Dương",
      "Phú Hựu",
      "Tân Nhuận Đông",
      "Tân Phú Trung",
      "Thanh Hưng",
      "An Hữu",
      "Mỹ Lợi",
      "Mỹ Đức Tây",
      "Mỹ Thiện",
      "Hậu Mỹ",
      "Hội Cư",
      "Cái Bè",
      "Hiệp Đức",
      "Bình Phú",
      "Ngũ Hiệp",
      "Long Tiên",
      "Mỹ Thành",
      "Thạnh Phú",
      "Mỹ Phước Tây",
      "Thanh Hòa",
      "Cai Lậy",
      "Nhị Quý",
      "Tân Phú",
      "Tân Phước 1",
      "Tân Phước 2",
      "Tân Phước 3",
      "Hưng Thạnh",
      "Tân Hương",
      "Châu Thành",
      "Long Hưng",
      "Long Định",
      "Vĩnh Kim",
      "Kim Sơn",
      "Bình Trưng",
      "Mỹ Tho",
      "Đạo Thạnh",
      "Mỹ Phong",
      "Thới Sơn",
      "Trung An",
      "Mỹ Tịnh An",
      "Lương Hòa Lạc",
      "Tân Thuận Bình",
      "Chợ Gạo",
      "An Thạnh Thủy",
      "Bình Ninh",
      "Gò Công Đông",
      "Tân Điền",
      "Tân Hòa",
      "Tân Đông",
      "Gia Thuận",
      "Vĩnh Bình",
      "Đồng Sơn",
      "Phú Thành",
      "Long Bình",
      "Vĩnh Hựu",
      "Gò Công",
      "Long Thuận",
      "Bình Xuân",
      "Sơn Quy",
      "Tân Thới",
      "Tân Phú Đông"
    ]
  },
  {
    "name": "Gia Lai",
    "wards": [
      "Canh Liên",
      "Nhơn Châu",
      "An Toàn",
      "Vân Canh",
      "Ia Púch",
      "Ia Mơ",
      "Ia Dom",
      "Ia Nan",
      "Ia Pnôn",
      "Canh Vinh",
      "An Hòa",
      "Phù Mỹ Đông",
      "Quy Nhơn Đông",
      "Tây Sơn",
      "Ia Chia",
      "Ia O",
      "Krong",
      "Pleiku",
      "Hội Phú",
      "Thống Nhất",
      "Diên Hồng",
      "An Phú",
      "Biển Hồ",
      "Gào",
      "Ia Ly",
      "Chư Păh",
      "Ia Khươl",
      "Ia Phí",
      "Chư Prông",
      "Bàu Cạn",
      "Ia Boòng",
      "Ia Lâu",
      "Ia Pia",
      "Ia Tôr",
      "Chư Sê",
      "Bờ Ngoong",
      "Ia Ko",
      "Al Bá",
      "Chư Pưh",
      "Ia Le",
      "Ia Hrú",
      "An Khê",
      "An Bình",
      "Cửu An",
      "Đak Pơ",
      "Ya Hội",
      "Kbang",
      "Kông Bơ La",
      "Tơ Tung",
      "Sơn Lang",
      "Đăk Roong",
      "Kông Chro",
      "Ya Ma",
      "Chư Krêy",
      "SRó",
      "Đăk Song",
      "Chơ Long",
      "Ayun Pa",
      "Ia Rbol",
      "Ia Sao",
      "Phú Thiện",
      "Chư A Thai",
      "Ia Hiao",
      "Pờ Tó",
      "Ia Pa",
      "Ia Tul",
      "Phú Túc",
      "Ia HDreh",
      "Ia Rsai",
      "Uar",
      "Đăk Đoa",
      "Kon Gang",
      "Ia Băng",
      "K'Dang",
      "Đăk Sơmei",
      "Mang Yang",
      "Lơ Pang",
      "Kon Chiêng",
      "Hra",
      "Ayun",
      "Ia Grai",
      "Ia KRai",
      "Ia Hrung",
      "Đức Cơ",
      "Ia Dơk",
      "Ia Krêl",
      "Ngô Mây",
      "Cát Tiến",
      "Đề Gi",
      "Hòa Hội",
      "Quy Nhơn",
      "Quy Nhơn Tây",
      "Quy Nhơn Nam",
      "Quy Nhơn Bắc",
      "Bình Định",
      "An Nhơn",
      "An Nhơn Đông",
      "An Nhơn Tây",
      "An Nhơn Nam",
      "An Nhơn Bắc",
      "Bồng Sơn",
      "Hoài Nhơn",
      "Tam Quan",
      "Hoài Nhơn Đông",
      "Hoài Nhơn Tây",
      "Hoài Nhơn Nam",
      "Hoài Nhơn Bắc",
      "Phù Cát",
      "Xuân An",
      "Hội Sơn",
      "Phù Mỹ",
      "An Lương",
      "Bình Dương",
      "Phù Mỹ Tây",
      "Phù Mỹ Nam",
      "Phù Mỹ Bắc",
      "Tuy Phước",
      "Tuy Phước Đông",
      "Tuy Phước Tây",
      "Tuy Phước Bắc",
      "Bình Khê",
      "Bình Phú",
      "Bình Hiệp",
      "Bình An",
      "Hoài Ân",
      "Ân Tường",
      "Kim Sơn",
      "Vạn Đức",
      "Ân Hảo",
      "Vĩnh Thạnh",
      "Vĩnh Thịnh",
      "Vĩnh Quang",
      "Vĩnh Sơn",
      "An Lão",
      "An Vinh"
    ]
  },
  {
    "name": "Hà Tĩnh",
    "wards": [
      "Thiên Cầm",
      "Kỳ Xuân",
      "Hoành Sơn",
      "Sơn Kim 1",
      "Sơn Kim 2",
      "Đan Hải",
      "Vũng Áng",
      "Sông Trí",
      "Hà Huy Tập",
      "Thành Sen",
      "Sơn Hồng",
      "Sơn Tây",
      "Sơn Giang",
      "Sơn Tiến",
      "Hương Sơn",
      "Tứ Mỹ",
      "Đức Minh",
      "Kim Hoa",
      "Vũ Quang",
      "Mai Hoa",
      "Thượng Đức",
      "Đức Đồng",
      "Hương Bình",
      "Hương Xuân",
      "Phúc Trạch",
      "Hà Linh",
      "Hương Đô",
      "Hương Phố",
      "Toàn Lưu",
      "Hải Ninh",
      "Kỳ Anh",
      "Kỳ Hoa",
      "Kỳ Văn",
      "Kỳ Khang",
      "Kỳ Lạc",
      "Kỳ Thượng",
      "Cẩm Xuyên",
      "Cẩm Duệ",
      "Cẩm Hưng",
      "Cẩm Lạc",
      "Cẩm Trung",
      "Yên Hòa",
      "Trần Phú",
      "Thạch Lạc",
      "Đồng Tiến",
      "Thạch Khê",
      "Cẩm Bình",
      "Thạch Hà",
      "Việt Xuyên",
      "Đông Kinh",
      "Thạch Xuân",
      "Xuân Lộc",
      "Can Lộc",
      "Bắc Hồng Lĩnh",
      "Nam Hồng Lĩnh",
      "Đức Thịnh",
      "Nghi Xuân",
      "Cổ Đạm",
      "Tiên Điền",
      "Đức Thọ",
      "Đức Quang",
      "Hương Khê",
      "Gia Hanh",
      "Trường Lưu",
      "Hồng Lộc",
      "Lộc Hà",
      "Mai Phụ",
      "Tùng Lộc",
      "Đồng Lộc"
    ]
  },
  {
    "name": "Hưng Yên",
    "wards": [
      "Hiệp Cường",
      "Đông Thái Ninh",
      "Sơn Nam",
      "Phố Hiến",
      "Hồng Châu",
      "Tân Hưng",
      "Hoàng Hoa Thám",
      "Tiên Lữ",
      "Tiên Hoa",
      "Quang Hưng",
      "Đoàn Đào",
      "Tiên Tiến",
      "Tống Trân",
      "Lương Bằng",
      "Nghĩa Dân",
      "Đức Hợp",
      "Ân Thi",
      "Xuân Trúc",
      "Phạm Ngũ Lão",
      "Nguyễn Trãi",
      "Hồng Quang",
      "Khoái Châu",
      "Triệu Việt Vương",
      "Việt Tiến",
      "Chí Minh",
      "Châu Ninh",
      "Yên Mỹ",
      "Việt Yên",
      "Hoàn Long",
      "Nguyễn Văn Linh",
      "Mỹ Hào",
      "Đường Hào",
      "Thượng Hồng",
      "Như Quỳnh",
      "Lạc Đạo",
      "Đại Đồng",
      "Nghĩa Trụ",
      "Phụng Công",
      "Văn Giang",
      "Mễ Sở",
      "Thái Bình",
      "Trần Lãm",
      "Trần Hưng Đạo",
      "Trà Lý",
      "Vũ Phúc",
      "Thái Thụy",
      "Đông Thụy Anh",
      "Bắc Thụy Anh",
      "Thụy Anh",
      "Nam Thụy Anh",
      "Bắc Thái Ninh",
      "Thái Ninh",
      "Nam Thái Ninh",
      "Tây Thái Ninh",
      "Tây Thụy Anh",
      "Tiền Hải",
      "Tây Tiền Hải",
      "Ái Quốc",
      "Đồng Châu",
      "Đông Tiền Hải",
      "Nam Cường",
      "Hưng Phú",
      "Đông Quan",
      "Nam Tiên Hưng",
      "Tiên Hưng",
      "Hưng Hà",
      "Tiên La",
      "Lê Quý Đôn",
      "Hồng Minh",
      "Thần Khê",
      "Diên Hà",
      "Ngự Thiên",
      "Long Hưng",
      "Kiến Xương",
      "Lê Lợi",
      "Quang Lịch",
      "Vũ Quý",
      "Bình Thanh",
      "Bình Định",
      "Hồng Vũ",
      "Bình Nguyên",
      "Trà Giang",
      "Vũ Thư",
      "Thư Trì",
      "Tân Thuận",
      "Thư Vũ",
      "Vũ Tiên",
      "Vạn Xuân",
      "Nam Tiền Hải",
      "Quỳnh Phụ",
      "Minh Thọ",
      "Nguyễn Du",
      "Quỳnh An",
      "Ngọc Lâm",
      "Đồng Bằng",
      "A Sào",
      "Phụ Dực",
      "Tân Tiến",
      "Đông Hưng",
      "Bắc Tiên Hưng",
      "Đông Tiên Hưng",
      "Nam Đông Hưng",
      "Bắc Đông Quan",
      "Bắc Đông Hưng"
    ]
  },
  {
    "name": "Khánh Hòa",
    "wards": [
      "Đô Vinh",
      "Phan Rang",
      "Bảo An",
      "Nam Ninh Hòa",
      "Vạn Hưng",
      "Tu Bông",
      "Vạn Thắng",
      "Đại Lãnh",
      "Bắc Cam Ranh",
      "Nam Cam Ranh",
      "Phước Dinh",
      "Nha Trang",
      "Bắc Nha Trang",
      "Ninh Chử",
      "Vĩnh Hải",
      "Cam Lâm",
      "Cam An",
      "Cam Hiệp",
      "Suối Dầu",
      "Đông Ninh Hòa",
      "Đặc Khu Trường Sa",
      "Đông Hải",
      "Nam Nha Trang",
      "Cam Ranh",
      "Cam Linh",
      "Ba Ngòi",
      "Bắc Ninh Hòa",
      "Ninh Hòa",
      "Tân Định",
      "Hòa Thắng",
      "Tây Ninh Hòa",
      "Hòa Trí",
      "Vạn Ninh",
      "Diên Khánh",
      "Diên Lạc",
      "Diên Điền",
      "Diên Lâm",
      "Diên Thọ",
      "Suối Hiệp",
      "Bắc Khánh Vĩnh",
      "Trung Khánh Vĩnh",
      "Tây Khánh Vĩnh",
      "Nam Khánh Vĩnh",
      "Khánh Vĩnh",
      "Khánh Sơn",
      "Tây Khánh Sơn",
      "Đông Khánh Sơn",
      "Ninh Phước",
      "Phước Hữu",
      "Phước Hậu",
      "Thuận Nam",
      "Cà Ná",
      "Phước Hà",
      "Ninh Hải",
      "Xuân Hải",
      "Thuận Bắc",
      "Công Hải",
      "Ninh Sơn",
      "Lâm Sơn",
      "Anh Dũng",
      "Mỹ Sơn",
      "Bác Ái Đông",
      "Bác Ái",
      "Bác Ái Tây",
      "Mỹ Bình"
    ]
  },
  {
    "name": "Lai Châu",
    "wards": [
      "Tà Tổng",
      "Mù Cả",
      "Thu Lũm",
      "Pa Ủ",
      "Nậm Cuổi",
      "Nậm Mạ",
      "Lê Lợi",
      "Nậm Hàng",
      "Mường Kim",
      "Khoen On",
      "Than Uyên",
      "Mường Than",
      "Pắc Ta",
      "Nậm Sỏ",
      "Tân Uyên",
      "Mường Khoa",
      "Bản Bo",
      "Bình Lư",
      "Tả Lèng",
      "Khun Há",
      "Tân Phong",
      "Đoàn Kết",
      "Sin Suối Hồ",
      "Phong Thổ",
      "Sì Lở Lầu",
      "Dào San",
      "Khổng Lào",
      "Tủa Sín Chải",
      "Sìn Hồ",
      "Hồng Thu",
      "Nậm Tăm",
      "Pu Sam Cáp",
      "Mường Mô",
      "Hua Bun",
      "Pa Tần",
      "Bum Nưa",
      "Bum Tở",
      "Mường Tè"
    ]
  },
  {
    "name": "Lâm Đồng",
    "wards": [
      "Quảng Hòa",
      "Quảng Sơn",
      "Quảng Trực",
      "Ninh Gia",
      "Phan Rí Cửa",
      "Tuy Phong",
      "Hòa Thắng",
      "Đặc Khu Phú Quý",
      "Hồng Thái",
      "Đạ Huoai 3",
      "Xuân Hương-Đà Lạt",
      "Cam Ly-Đà Lạt",
      "Lâm Viên-Đà Lạt",
      "Xuân Trường-Đà Lạt",
      "Lang Biang-Đà Lạt",
      "1 Bảo Lộc",
      "2 Bảo Lộc",
      "3 Bảo Lộc",
      "B'Lao",
      "Đơn Dương",
      "Ka Đô",
      "Quảng Lập",
      "D'Ran",
      "Hiệp Thạnh",
      "Lạc Dương",
      "Đức Trọng",
      "Tân Hội",
      "Tà Hine",
      "Tà Năng",
      "Đinh Văn-Lâm Hà",
      "Phú Sơn-Lâm Hà",
      "Nam Hà-Lâm Hà",
      "Nam Ban-Lâm Hà",
      "Tân Hà-Lâm Hà",
      "Phúc Thọ-Lâm Hà",
      "Đam Rông 1",
      "Đam Rông 2",
      "Đam Rông 3",
      "Đam Rông 4",
      "Di Linh",
      "Hòa Ninh",
      "Hòa Bắc",
      "Đinh Trang Thượng",
      "Bảo Thuận",
      "Sơn Điền",
      "Gia Hiệp",
      "Bảo Lâm 1",
      "Bảo Lâm 2",
      "Bảo Lâm 3",
      "Bảo Lâm 4",
      "Bảo Lâm 5",
      "Đạ Huoai",
      "Đạ Huoai 2",
      "Đạ Tẻh",
      "Đạ Tẻh 2",
      "Đạ Tẻh 3",
      "Cát Tiên",
      "Cát Tiên 2",
      "Cát Tiên 3",
      "Đắk Wil",
      "Nam Dong",
      "Cư Jút",
      "Thuận An",
      "Đức Lập",
      "Đắk Mil",
      "Đắk Sắk",
      "Nam Đà",
      "Krông Nô",
      "Nâm Nung",
      "Quảng Phú",
      "Đắk Song",
      "Đức An",
      "Thuận Hạnh",
      "Trường Xuân",
      "Tà Đùng",
      "Quảng Khê",
      "Bắc Gia Nghĩa",
      "Nam Gia Nghĩa",
      "Đông Gia Nghĩa",
      "Quảng Tân",
      "Tuy Đức",
      "Kiến Đức",
      "Nhân Cơ",
      "Quảng Tín",
      "Vĩnh Hảo",
      "Liên Hương",
      "Bắc Bình",
      "Hải Ninh",
      "Phan Sơn",
      "Sông Lũy",
      "Lương Sơn",
      "Đông Giang",
      "Tân Lập",
      "Tân Minh",
      "Hàm Tân",
      "Sơn Mỹ",
      "La Gi",
      "Phước Hội",
      "Tân Hải",
      "Nghị Đức",
      "Bắc Ruộng",
      "Đồng Kho",
      "Tánh Linh",
      "Suối Kiết",
      "Nam Thành",
      "Đức Linh",
      "Hoài Đức",
      "Trà Tân",
      "La Dạ",
      "Hàm Thuận Bắc",
      "Hàm Thuận",
      "Hồng Sơn",
      "Hàm Liêm",
      "Hàm Thắng",
      "Bình Thuận",
      "Mũi Né",
      "Phú Thủy",
      "Phan Thiết",
      "Tiến Thành",
      "Tuyên Quang",
      "Hàm Thạnh",
      "Hàm Kiệm",
      "Tân Thành",
      "Hàm Thuận Nam"
    ]
  },
  {
    "name": "Lạng Sơn",
    "wards": [
      "Châu Sơn",
      "Đình Lập",
      "Kiên Mộc",
      "Thất Khê",
      "Đoàn Kết",
      "Tân Tiến",
      "Tràng Định",
      "Quốc Khánh",
      "Kháng Chiến",
      "Quốc Việt",
      "Bình Gia",
      "Tân Văn",
      "Hồng Phong",
      "Hoa Thám",
      "Quý Hòa",
      "Thiện Hòa",
      "Thiện Thuật",
      "Thiện Long",
      "Bắc Sơn",
      "Hưng Vũ",
      "Vũ Lăng",
      "Nhất Hòa",
      "Vũ Lễ",
      "Tân Tri",
      "Văn Quan",
      "Điềm He",
      "Yên Phúc",
      "Tri Lễ",
      "Tân Đoàn",
      "Khánh Khê",
      "Na Sầm",
      "Tân Thanh",
      "Thụy Hùng",
      "Văn Lãng",
      "Hội Hoan",
      "Lộc Bình",
      "Mẫu Sơn",
      "Na Dương",
      "Lợi Bác",
      "Thống Nhất",
      "Xuân Dương",
      "Khuất Xá",
      "Thái Bình",
      "Hữu Lũng",
      "Tuấn Sơn",
      "Tân Thành",
      "Vân Nham",
      "Thiện Tân",
      "Yên Bình",
      "Hữu Liên",
      "Cai Kinh",
      "Chi Lăng",
      "Quan Sơn",
      "Chiến Thắng",
      "Nhân Lý",
      "Bằng Mạc",
      "Vạn Linh",
      "Đồng Đăng",
      "Cao Lộc",
      "Công Sơn",
      "Ba Sơn",
      "Tam Thanh",
      "Lương Văn Tri",
      "Hoàng Văn Thụ",
      "Đông Kinh"
    ]
  },
  {
    "name": "Lào Cai",
    "wards": [
      "Phong Dụ Thượng",
      "Nậm Có",
      "Nậm Xé",
      "Tà Si Láng",
      "Chế Tạo",
      "Lao Chải",
      "Cát Thịnh",
      "Ngũ Chỉ Sơn",
      "Khao Mang",
      "Mù Cang Chải",
      "Púng Luông",
      "Trạm Tấu",
      "Hạnh Phúc",
      "Phình Hồ",
      "Liên Sơn",
      "Nghĩa Lộ",
      "Trung Tâm",
      "Cầu Thia",
      "Tú Lệ",
      "Gia Hội",
      "Sơn Lương",
      "Văn Chấn",
      "Thượng Bằng La",
      "Chấn Thịnh",
      "Nghĩa Tâm",
      "Phong Dụ Hạ",
      "Châu Quế",
      "Lâm Giang",
      "Đông Cuông",
      "Tân Hợp",
      "Mậu A",
      "Xuân Ái",
      "Mỏ Vàng",
      "Lâm Thượng",
      "Lục Yên",
      "Tân Lĩnh",
      "Khánh Hòa",
      "Phúc Lợi",
      "Mường Lai",
      "Cảm Nhân",
      "Yên Thành",
      "Thác Bà",
      "Yên Bình",
      "Bảo Ái",
      "Văn Phú",
      "Yên Bái",
      "Nam Cường",
      "Âu Lâu",
      "Trấn Yên",
      "Hưng Khánh",
      "Lương Thịnh",
      "Việt Hồng",
      "Quy Mông",
      "Phong Hải",
      "Xuân Quang",
      "Bảo Thắng",
      "Tằng Loỏng",
      "Gia Phú",
      "Cam Đường",
      "Lào Cai",
      "Cốc San",
      "Hợp Thành",
      "Mường Hum",
      "Dền Sáng",
      "Y Tý",
      "A Mú Sung",
      "Trịnh Tường",
      "Bản Xèo",
      "Bát Xát",
      "Bảo Yên",
      "Nghĩa Đô",
      "Thượng Hà",
      "Xuân Hòa",
      "Phúc Khánh",
      "Bảo Hà",
      "Võ Lao",
      "Khánh Yên",
      "Văn Bàn",
      "Dương Quỳ",
      "Chiềng Ken",
      "Minh Lương",
      "Nậm Chầy",
      "Mường Bo",
      "Bản Hồ",
      "Sa Pa",
      "Tả Phìn",
      "Tả Van",
      "Cốc Lầu",
      "Bảo Nhai",
      "Bản Liền",
      "Bắc Hà",
      "Tả Củ Tỷ",
      "Lùng Phình",
      "Pha Long",
      "Mường Khương",
      "Bản Lầu",
      "Cao Sơn",
      "Si Ma Cai",
      "Sín Chéng"
    ]
  },
  {
    "name": "Nghệ An",
    "wards": [
      "Hữu Khuông",
      "Huồi Tụ",
      "Bắc Lý",
      "Keng Đu",
      "Mường Lống",
      "Mỹ Lý",
      "Bình Chuẩn",
      "Châu Bình",
      "Lưỡng Minh",
      "Quỳnh Anh",
      "Anh Sơn",
      "Yên Xuân",
      "Nhân Hòa",
      "Anh Sơn Đông",
      "Vĩnh Tường",
      "Thành Bình Thọ",
      "Con Cuông",
      "Môn Sơn",
      "Mậu Thạch",
      "Cam Phục",
      "Châu Khê",
      "Diễn Châu",
      "Đức Châu",
      "Quảng Châu",
      "Hải Châu",
      "Tân Châu",
      "An Châu",
      "Minh Châu",
      "Hùng Châu",
      "Đô Lương",
      "Bạch Ngọc",
      "Văn Hiến",
      "Bạch Hà",
      "Thuần Trung",
      "Lương Sơn",
      "Hoàng Mai",
      "Tân Mai",
      "Quỳnh Mai",
      "Hưng Nguyên",
      "Hưng Nguyên Nam",
      "Lam Thành",
      "Mường Xén",
      "Hữu Kiệm",
      "Nậm Cắn",
      "Chiêu Lưu",
      "Na Loi",
      "Mường Típ",
      "Na Ngoi",
      "Vạn An",
      "Nam Đàn",
      "Đại Huệ",
      "Thiên Nhẫn",
      "Kim Liên",
      "Nghĩa Đàn",
      "Nghĩa Thọ",
      "Nghĩa Lâm",
      "Nghĩa Mai",
      "Nghĩa Hưng",
      "Nghĩa Khánh",
      "Nghĩa Lộc",
      "Nghi Lộc",
      "Phúc Lộc",
      "Đông Lộc",
      "Trung Lộc",
      "Thần Lĩnh",
      "Hải Lộc",
      "Văn Kiều",
      "Tiền Phong",
      "Tri Lễ",
      "Mường Quàng",
      "Thông Thụ",
      "Quỳ Châu",
      "Châu Tiến",
      "Hùng Chân",
      "Quỳ Hợp",
      "Tam Hợp",
      "Châu Lộc",
      "Châu Hồng",
      "Mường Ham",
      "Mường Chọng",
      "Minh Hợp",
      "Quỳnh Lưu",
      "Quỳnh Văn",
      "Quỳnh Tam",
      "Quỳnh Phú",
      "Quỳnh Sơn",
      "Quỳnh Thắng",
      "Tân Kỳ",
      "Tân Phú",
      "Tân An",
      "Nghĩa Đồng",
      "Giai Xuân",
      "Nghĩa Hành",
      "Tiên Đồng",
      "Cát Ngạn",
      "Tam Đồng",
      "Hạnh Lâm",
      "Sơn Lâm",
      "Hoa Quân",
      "Kim Bảng",
      "Bích Hào",
      "Đại Đồng",
      "Xuân Lâm",
      "Thái Hòa",
      "Tây Hiếu",
      "Đông Hiếu",
      "Tam Quang",
      "Tam Thái",
      "Tương Dương",
      "Yên Na",
      "Yên Hòa",
      "Nga My",
      "Nhôn Mai",
      "Thành Vinh",
      "Vinh Hưng",
      "Vinh Phú",
      "Vinh Lộc",
      "Yên Thành",
      "Quan Thành",
      "Hợp Minh",
      "Vân Tụ",
      "Vân Du",
      "Quang Đồng",
      "Giai Lạc",
      "Bình Minh",
      "Đông Thành",
      "Yên Trung",
      "Cửa Lò",
      "Quế Phong",
      "Trường Vinh"
    ]
  },
  {
    "name": "Ninh Bình",
    "wards": [
      "Duy Tân",
      "Duy Hà",
      "Tây Hoa Lư",
      "Thanh Bình",
      "Thanh Liêm",
      "Hà Nam",
      "Tiên Sơn",
      "Mỹ Lộc",
      "Hoa Lư",
      "Nam Hoa Lư",
      "Đông Hoa Lư",
      "Tam Điệp",
      "Yên Sơn",
      "Trung Sơn",
      "Yên Thắng",
      "Gia Viễn",
      "Đại Hoàng",
      "Gia Hưng",
      "Gia Phong",
      "Gia Vân",
      "Gia Trấn",
      "Nho Quan",
      "Gia Lâm",
      "Gia Tường",
      "Phú Sơn",
      "Cúc Phương",
      "Phú Long",
      "Thanh Sơn",
      "Quỳnh Lưu",
      "Yên Khánh",
      "Khánh Nhạc",
      "Khánh Thiện",
      "Khánh Hội",
      "Khánh Trung",
      "Yên Mô",
      "Yên Từ",
      "Yên Mạc",
      "Đồng Thái",
      "Chất Bình",
      "Kim Sơn",
      "Quang Thiện",
      "Phát Diệm",
      "Lai Thành",
      "Định Hóa",
      "Bình Minh",
      "Kim Đông",
      "Nam Định",
      "Thiên Trường",
      "Đông A",
      "Thành Nam",
      "Trường Thi",
      "Hồng Quang",
      "Nam Trực",
      "Nam Minh",
      "Nam Đồng",
      "Nam Ninh",
      "Nam Hồng",
      "Minh Tân",
      "Hiển Khánh",
      "Vụ Bản",
      "Liên Minh",
      "Ý Yên",
      "Yên Đồng",
      "Yên Cường",
      "Vạn Thắng",
      "Vũ Dương",
      "Tân Minh",
      "Phong Doanh",
      "Cổ Lễ",
      "Ninh Giang",
      "Cát Thành",
      "Trực Ninh",
      "Quang Hưng",
      "Minh Thái",
      "Ninh Cường",
      "Xuân Trường",
      "Xuân Hưng",
      "Xuân Giang",
      "Xuân Hồng",
      "Hải Hậu",
      "Hải Anh",
      "Hải Tiến",
      "Hải Hưng",
      "Hải An",
      "Hải Quang",
      "Hải Xuân",
      "Hải Thịnh",
      "Đồng Thịnh",
      "Nghĩa Hưng",
      "Nghĩa Sơn",
      "Hồng Phong",
      "Quỹ Nhất",
      "Nghĩa Lâm",
      "Rạng Đông",
      "Vị Khê",
      "Giao Minh",
      "Giao Hoà",
      "Giao Thuỷ",
      "Giao Phúc",
      "Giao Hưng",
      "Giao Bình",
      "Giao Ninh",
      "Đồng Văn",
      "Lê Hồ",
      "Nguyễn Uý",
      "Lý Thường Kiệt",
      "Kim Thanh",
      "Tam Chúc",
      "Phù Vân",
      "Châu Sơn",
      "Liêm Tuyền",
      "Bình Lục",
      "Bình Mỹ",
      "Bình An",
      "Bình Giang",
      "Bình Sơn",
      "Liêm Hà",
      "Tân Thanh",
      "Thanh Lâm",
      "Lý Nhân",
      "Nam Xang",
      "Bắc Lý",
      "Vĩnh Trụ",
      "Trần Thương",
      "Nhân Hà",
      "Nam Lý",
      "Kim Bảng",
      "Duy Tiên",
      "Phủ Lý"
    ]
  },
  {
    "name": "Phú Thọ",
    "wards": [
      "Trung Sơn",
      "Thu Cúc",
      "Tiền Phong",
      "Liên Sơn",
      "Mai Châu",
      "Pà Cò",
      "Thống Nhất",
      "Đạo Trù",
      "Phúc Yên",
      "Xuân Hòa",
      "Lương Sơn",
      "Cao Phong",
      "Mường Thàng",
      "Thung Nai",
      "Đà Bắc",
      "Cao Sơn",
      "Đức Nhàn",
      "Quy Đức",
      "Tân Pheo",
      "Kim Bôi",
      "Mường Động",
      "Dũng Tiến",
      "Hợp Kim",
      "Nật Sơn",
      "Lạc Sơn",
      "Mường Vang",
      "Đại Đồng",
      "Ngọc Sơn",
      "Nhân Nghĩa",
      "Quyết Thắng",
      "Thượng Cốc",
      "Yên Phú",
      "Lạc Thủy",
      "An Bình",
      "An Nghĩa",
      "Cao Dương",
      "Bao La",
      "Mai Hạ",
      "Tân Mai",
      "Tân Lạc",
      "Mường Bi",
      "Toàn Thắng",
      "Mường Hoa",
      "Vân Sơn",
      "Yên Thủy",
      "Lạc Lương",
      "Yên Trị",
      "Thịnh Minh",
      "Hòa Bình",
      "Kỳ Sơn",
      "Tân Hòa",
      "Tam Sơn",
      "Sông Lô",
      "Hải Lựu",
      "Yên Lãng",
      "Lập Thạch",
      "Tiên Lữ",
      "Thái Hòa",
      "Liên Hòa",
      "Hợp Lý",
      "Sơn Đông",
      "Tam Đảo",
      "Đại Đình",
      "Tam Dương",
      "Hội Thịnh",
      "Hoàng An",
      "Tam Dương Bắc",
      "Vĩnh Tường",
      "Thổ Tang",
      "Vĩnh Hưng",
      "Vĩnh An",
      "Vĩnh Phú",
      "Vĩnh Thành",
      "Yên Lạc",
      "Tề Lỗ",
      "Liên Châu",
      "Tam Hồng",
      "Nguyệt Đức",
      "Bình Nguyên",
      "Xuân Lãng",
      "Bình Xuyên",
      "Bình Tuyền",
      "Vĩnh Phúc",
      "Vĩnh Yên",
      "Vân Phú",
      "Hy Cương",
      "Lâm Thao",
      "Xuân Lũng",
      "Phùng Nguyên",
      "Bản Nguyên",
      "Phong Châu",
      "Phú Thọ",
      "Âu Cơ",
      "Phù Ninh",
      "Dân Chủ",
      "Phú Mỹ",
      "Trạm Thản",
      "Bình Phú",
      "Thanh Ba",
      "Quảng Yên",
      "Hoàng Cương",
      "Đông Thành",
      "Chí Tiên",
      "Liên Minh",
      "Đoan Hùng",
      "Tây Cốc",
      "Chân Mộng",
      "Chí Đám",
      "Bằng Luân",
      "Hạ Hòa",
      "Đan Thượng",
      "Yên Kỳ",
      "Vĩnh Chân",
      "Văn Lang",
      "Hiền Lương",
      "Cẩm Khê",
      "Phú Khê",
      "Hùng Việt",
      "Đồng Lương",
      "Tiên Lương",
      "Vân Bán",
      "Tam Nông",
      "Thọ Văn",
      "Vạn Xuân",
      "Hiền Quan",
      "Thanh Thủy",
      "Đào Xá",
      "Tu Vũ",
      "Thanh Sơn",
      "Võ Miếu",
      "Văn Miếu",
      "Cự Đồng",
      "Hương Cần",
      "Yên Sơn",
      "Khả Cửu",
      "Tân Sơn",
      "Minh Đài",
      "Lai Đồng",
      "Xuân Đài",
      "Long Cốc",
      "Yên Lập",
      "Thượng Long",
      "Sơn Lương",
      "Xuân Viên",
      "Minh Hòa",
      "Việt Trì",
      "Nông Trang",
      "Thanh Miếu"
    ]
  },
  {
    "name": "Quảng Ngãi",
    "wards": [
      "Đắk Long",
      "Ba Xa",
      "Cà Đam",
      "Vạn Tường",
      "Mô Rai",
      "Rơ Kơi",
      "Ia Đal",
      "Ia Tơi",
      "Tây Trà Bồng",
      "Đông Sơn",
      "Đặc Khu Lý Sơn",
      "Tịnh Khê",
      "Trương Quang Trọng",
      "An Phú",
      "Cẩm Thành",
      "Nghĩa Lộ",
      "Trà Câu",
      "Nguyễn Nghiêm",
      "Đức Phổ",
      "Khánh Cường",
      "Sa Huỳnh",
      "Bình Minh",
      "Bình Chương",
      "Trường Giang",
      "Ba Gia",
      "Sơn Tịnh",
      "Thọ Phong",
      "Tư Nghĩa",
      "Vệ Giang",
      "Nghĩa Giang",
      "Trà Giang",
      "Nghĩa Hành",
      "Đình Cương",
      "Thiện Tín",
      "Phước Giang",
      "Long Phụng",
      "Mỏ Cày",
      "Mộ Đức",
      "Lân Phong",
      "Trà Bồng",
      "Đông Trà Bồng",
      "Tây Trà",
      "Thanh Bồng",
      "Sơn Hạ",
      "Sơn Linh",
      "Sơn Hà",
      "Sơn Thủy",
      "Sơn Kỳ",
      "Sơn Tây",
      "Sơn Tây Thượng",
      "Sơn Tây Hạ",
      "Minh Long",
      "Sơn Mai",
      "Ba Vì",
      "Ba Tô",
      "Ba Dinh",
      "Ba Tơ",
      "Ba Vinh",
      "Ba Động",
      "Đặng Thùy Trâm",
      "Bình Sơn",
      "Kon Tum",
      "Đắk Cấm",
      "Đắk Bla",
      "Ngọk Bay",
      "Ia Chim",
      "Đắk Rơ Wa",
      "Đắk PXi",
      "Đắk Mar",
      "Đắk Ui",
      "Ngok Réo",
      "Đắk Hà",
      "Ngọk Tụ",
      "Đắk Tô",
      "Kon Đào",
      "Đắk Sao",
      "Đắk Tờ Kan",
      "Tu Mơ Rông",
      "Măng Ri",
      "Bờ Y",
      "Sa Loong",
      "Dục Nông",
      "Xốp",
      "Ngọc Linh",
      "Đắk Blô",
      "Đắk Pék",
      "Đắk Môn",
      "Sa Thầy",
      "Sa Bình",
      "Ya Ly",
      "Đắk Kôi",
      "Kon Braih",
      "Đắk Rve",
      "Măng Đen",
      "Măng Buk",
      "Kon Plông"
    ]
  },
  {
    "name": "Quảng Ninh",
    "wards": [
      "Vàng Danh",
      "Đường Hoa",
      "Hoành Bồ",
      "Thống Nhất",
      "Đông Ngũ",
      "Hải Lạng",
      "Hải Hòa",
      "Hà An",
      "Liên Hòa",
      "Quang Hanh",
      "Tuần Châu",
      "Hà Tu",
      "An Sinh",
      "Vĩnh Thực",
      "Quảng Hà",
      "Cái Chiên",
      "Điền Xá",
      "Việt Hưng",
      "Bình Khê",
      "Mạo Khê",
      "Hoàng Quế",
      "Yên Tử",
      "Đông Mai",
      "Hiệp Hòa",
      "Quảng Yên",
      "Phong Cốc",
      "Bãi Cháy",
      "Hà Lầm",
      "Cao Xanh",
      "Hồng Gai",
      "Hạ Long",
      "Quảng La",
      "Mông Dương",
      "Cẩm Phả",
      "Cửa Ông",
      "Lương Minh",
      "Kỳ Thượng",
      "Quảng Tân",
      "Quảng Đức",
      "Hoành Mô",
      "Lục Hồn",
      "Hải Sơn",
      "Hải Ninh",
      "Móng Cái 1",
      "Móng Cái 2",
      "Móng Cái 3",
      "Đầm Hà",
      "Đặc Khu Vân Đồn",
      "Đặc Khu Cô Tô",
      "Đông Triều",
      "Uông Bí",
      "Tiên Yên",
      "Ba Chẽ",
      "Bình Liêu"
    ]
  },
  {
    "name": "Quảng Trị",
    "wards": [
      "Phú Trạch",
      "Đặc Khu Cồn Cỏ",
      "Tân Thành",
      "Đồng Hới",
      "Đồng Thuận",
      "Đồng Sơn",
      "Ba Đồn",
      "Bắc Gianh",
      "Nam Gianh",
      "Nam Ba Đồn",
      "Dân Hóa",
      "Kim Điền",
      "Kim Phú",
      "Minh Hóa",
      "Tuyên Lâm",
      "Tuyên Sơn",
      "Đồng Lê",
      "Tuyên Phú",
      "Tuyên Bình",
      "Tuyên Hóa",
      "Tân Gianh",
      "Trung Thuần",
      "Quảng Trạch",
      "Hòa Trạch",
      "Thượng Trạch",
      "Phong Nha",
      "Bắc Trạch",
      "Đông Trạch",
      "Hoàn Lão",
      "Bố Trạch",
      "Nam Trạch",
      "Quảng Ninh",
      "Ninh Châu",
      "Trường Ninh",
      "Trường Sơn",
      "Lệ Thủy",
      "Cam Hồng",
      "Sen Ngư",
      "Tân Mỹ",
      "Trường Phú",
      "Lệ Ninh",
      "Kim Ngân",
      "Vĩnh Linh",
      "Cửa Tùng",
      "Vĩnh Hoàng",
      "Vĩnh Thủy",
      "Bến Quan",
      "Cồn Tiên",
      "Cửa Việt",
      "Gio Linh",
      "Bến Hải",
      "Cam Lộ",
      "Hiếu Giang",
      "La Lay",
      "Tà Rụt",
      "Đakrông",
      "Ba Lòng",
      "Hướng Hiệp",
      "Hướng Lập",
      "Hướng Phùng",
      "Khe Sanh",
      "Tân Lập",
      "Lao Bảo",
      "Lìa",
      "A Dơi",
      "Đông Hà",
      "Nam Đông Hà",
      "Triệu Phong",
      "Ái Tử",
      "Triệu Bình",
      "Triệu Cơ",
      "Nam Cửa Việt",
      "Quảng Trị",
      "Diên Sanh",
      "Mỹ Thủy",
      "Hải Lăng",
      "Nam Hải Lăng",
      "Vĩnh Định"
    ]
  },
  {
    "name": "Sơn La",
    "wards": [
      "Mường Bám",
      "Phiêng Khoài",
      "Chiềng Cơi",
      "Suối Tọ",
      "Mường Lạn",
      "Tân Yên",
      "Ngọc Chiến",
      "Mường Lèo",
      "Tô Hiệu",
      "Chiềng An",
      "Chiềng Sinh",
      "Mộc Sơn",
      "Vân Sơn",
      "Thảo Nguyên",
      "Đoàn Kết",
      "Lóng Sập",
      "Chiềng Sơn",
      "Vân Hồ",
      "Song Khủa",
      "Tô Múa",
      "Xuân Nha",
      "Quỳnh Nhai",
      "Mường Chiên",
      "Mường Giôn",
      "Mường Sại",
      "Thuận Châu",
      "Chiềng La",
      "Nậm Lầu",
      "Muổi Nọi",
      "Mường Khiêng",
      "Co Mạ",
      "Bình Thuận",
      "Mường É",
      "Long Hẹ",
      "Mường La",
      "Chiềng Lao",
      "Mường Bú",
      "Chiềng Hoa",
      "Bắc Yên",
      "Tà Xùa",
      "Tạ Khoa",
      "Xím Vàng",
      "Pắc Ngà",
      "Chiềng Sại",
      "Phù Yên",
      "Gia Phù",
      "Tường Hạ",
      "Mường Cơi",
      "Mường Bang",
      "Tân Phong",
      "Kim Bon",
      "Yên Châu",
      "Chiềng Hặc",
      "Lóng Phiêng",
      "Yên Sơn",
      "Chiềng Mai",
      "Mai Sơn",
      "Phiêng Pằn",
      "Chiềng Mung",
      "Phiêng Cằm",
      "Mường Chanh",
      "Tà Hộc",
      "Chiềng Sung",
      "Bó Sinh",
      "Chiềng Khương",
      "Mường Hung",
      "Chiềng Khoong",
      "Mường Lầm",
      "Nậm Ty",
      "Sông Mã",
      "Huổi Một",
      "Chiềng Sơ",
      "Sốp Cộp",
      "Púng Bánh",
      "Mộc Châu"
    ]
  },
  {
    "name": "Tây Ninh",
    "wards": [
      "Dương Minh Châu",
      "Ninh Thạnh",
      "Cầu Khởi",
      "Lộc Ninh",
      "Thạnh Bình",
      "Trà Vong",
      "Tân Châu",
      "Tân Thành",
      "Tân Phú",
      "Tân Ninh",
      "Bình Minh",
      "Châu Thành",
      "Đức Lập",
      "Mỹ Hạnh",
      "Tuyên Thạnh",
      "Hậu Thạnh",
      "Long An",
      "Mỹ Thạnh",
      "Vĩnh Hưng",
      "Khánh Hưng",
      "Tuyên Bình",
      "Nhựt Tảo",
      "Thủ Thừa",
      "Lương Hòa",
      "Long Hoa",
      "Hòa Thành",
      "Thanh Điền",
      "Trảng Bàng",
      "An Tịnh",
      "Gò Dầu",
      "Gia Lộc",
      "Hưng Thuận",
      "Phước Chỉ",
      "Thạnh Đức",
      "Phước Thạnh",
      "Truông Mít",
      "Tân Đông",
      "Tân Hội",
      "Tân Hòa",
      "Tân Lập",
      "Tân Biên",
      "Phước Vinh",
      "Hòa Hội",
      "Ninh Điền",
      "Hảo Đước",
      "Long Chữ",
      "Long Thuận",
      "Bến Cầu",
      "Hưng Điền",
      "Vĩnh Thạnh",
      "Tân Hưng",
      "Vĩnh Châu",
      "Bình Hiệp",
      "Kiến Tường",
      "Bình Hòa",
      "Mộc Hóa",
      "Nhơn Hòa Lập",
      "Nhơn Ninh",
      "Tân Thạnh",
      "Bình Thành",
      "Thạnh Phước",
      "Thạnh Hóa",
      "Tân Tây",
      "Mỹ An",
      "Tân Long",
      "Mỹ Quý",
      "Đông Thành",
      "Đức Huệ",
      "An Ninh",
      "Hiệp Hòa",
      "Hậu Nghĩa",
      "Hòa Khánh",
      "Đức Hòa",
      "Thạnh Lợi",
      "Bình Đức",
      "Bến Lức",
      "Mỹ Yên",
      "Long Cang",
      "Rạch Kiến",
      "Mỹ Lệ",
      "Tân Lân",
      "Cần Đước",
      "Long Hựu",
      "Phước Lý",
      "Mỹ Lộc",
      "Cần Giuộc",
      "Phước Vĩnh Tây",
      "Tân Tập",
      "Vàm Cỏ",
      "Tân Trụ",
      "Thuận Mỹ",
      "An Lục Long",
      "Tầm Vu",
      "Vĩnh Công",
      "Tân An",
      "Khánh Hậu"
    ]
  },
  {
    "name": "Thái Nguyên",
    "wards": [
      "Thượng Quan",
      "Sảng Mộc",
      "Phú Bình",
      "Điềm Thụy",
      "Gia Sàng",
      "Phan Đình Phùng",
      "Tích Lương",
      "Linh Sơn",
      "Phúc Thuận",
      "Thành Công",
      "Tân Thành",
      "Kha Sơn",
      "Tân Khánh",
      "Đồng Hỷ",
      "Quang Sơn",
      "Trại Cau",
      "Nam Hòa",
      "Văn Hán",
      "Văn Lăng",
      "Sông Công",
      "Bá Xuyên",
      "Bách Quang",
      "Phú Lương",
      "Vô Tranh",
      "Yên Trạch",
      "Hợp Thành",
      "Định Hóa",
      "Bình Yên",
      "Trung Hội",
      "Phượng Tiến",
      "Phú Đình",
      "Bình Thành",
      "Kim Phượng",
      "Lam Vỹ",
      "Võ Nhai",
      "Dân Tiến",
      "Nghinh Tường",
      "Thần Sa",
      "La Hiên",
      "Tràng Xá",
      "Quyết Thắng",
      "Quan Triều",
      "Tân Cương",
      "Đại Phúc",
      "Đại Từ",
      "Đức Lương",
      "Phú Thịnh",
      "La Bằng",
      "Phú Lạc",
      "An Khánh",
      "Quân Chu",
      "Vạn Phú",
      "Phú Xuyên",
      "Phổ Yên",
      "Vạn Xuân",
      "Trung Thành",
      "Phúc Lộc",
      "Thượng Minh",
      "Đồng Phúc",
      "Bằng Vân",
      "Bằng Thành",
      "Nghiên Loan",
      "Cao Minh",
      "Ba Bể",
      "Chợ Rã",
      "Ngân Sơn",
      "Nà Phặc",
      "Hiệp Lực",
      "Nam Cường",
      "Quảng Bạch",
      "Yên Thịnh",
      "Chợ Đồn",
      "Yên Phong",
      "Nghĩa Tá",
      "Phủ Thông",
      "Cẩm Giàng",
      "Vĩnh Thông",
      "Bạch Thông",
      "Phong Quang",
      "Đức Xuân",
      "Bắc Kạn",
      "Văn Lang",
      "Cường Lợi",
      "Na Rì",
      "Trần Phú",
      "Côn Minh",
      "Xuân Dương",
      "Tân Kỳ",
      "Thanh Mai",
      "Thanh Thịnh",
      "Chợ Mới",
      "Yên Bình"
    ]
  },
  {
    "name": "Thanh Hóa",
    "wards": [
      "Thiệu Quang",
      "Thọ Phú",
      "Trung Lý",
      "Trung Sơn",
      "Mường Mìn",
      "Na Mèo",
      "Sơn Điện",
      "Sơn Thủy",
      "Tam Lư",
      "Tam Thanh",
      "Quang Chiểu",
      "Tam Chung",
      "Nhi Sơn",
      "Pù Nhi",
      "Công Chính",
      "Phú Xuân",
      "Thanh Kỳ",
      "Xuân Thái",
      "Yên Thọ",
      "Mường Lý",
      "Yên Khương",
      "Yên Thắng",
      "Mường Lát",
      "Mường Chanh",
      "Thiệu Trung",
      "Bát Mọt",
      "Luận Thành",
      "Lương Sơn",
      "Vạn Xuân",
      "Tân Thành",
      "Hải Bình",
      "Yên Nhân",
      "Định Hòa",
      "Hàm Rồng",
      "Hoạt Giang",
      "Vạn Lộc",
      "Đông Quang",
      "Quảng Phú",
      "Đông Sơn",
      "Đông Tiến",
      "Nguyệt Viên",
      "Sầm Sơn",
      "Nam Sầm Sơn",
      "Bỉm Sơn",
      "Quang Trung",
      "Ngọc Sơn",
      "Tân Dân",
      "Hải Lĩnh",
      "Tĩnh Gia",
      "Đào Duy Tư",
      "Trúc Lâm",
      "Nghi Sơn",
      "Các Sơn",
      "Trường Lâm",
      "Tống Sơn",
      "Hà Long",
      "Lĩnh Toại",
      "Triệu Lộc",
      "Đông Thành",
      "Hậu Lộc",
      "Hoa Lộc",
      "Nga Sơn",
      "Nga Thắng",
      "Hồ Vương",
      "Tân Tiến",
      "Nga An",
      "Ba Đình",
      "Hoằng Hóa",
      "Hoằng Tiến",
      "Hoằng Thanh",
      "Hoằng Lộc",
      "Hoằng Châu",
      "Hoằng Sơn",
      "Hoằng Phú",
      "Hoằng Giang",
      "Lưu Vệ",
      "Quảng Yên",
      "Quảng Ngọc",
      "Quảng Ninh",
      "Quảng Bình",
      "Tiên Trang",
      "Quảng Chính",
      "Nông Cống",
      "Thắng Lợi",
      "Trung Chính",
      "Trường Văn",
      "Thăng Bình",
      "Tượng Lĩnh",
      "Thiệu Tiến",
      "Thiệu Toán",
      "Yên Định",
      "Yên Trường",
      "Yên Phú",
      "Quý Lộc",
      "Yên Ninh",
      "Định Tân",
      "Thọ Xuân",
      "Thọ Long",
      "Xuân Hòa",
      "Sao Vàng",
      "Lam Sơn",
      "Thọ Lập",
      "Xuân Tín",
      "Xuân Lập",
      "Vĩnh Lộc",
      "Tây Đô",
      "Biện Thượng",
      "Triệu Sơn",
      "Thọ Bình",
      "Thọ Ngọc",
      "Hợp Tiến",
      "An Nông",
      "Tân Ninh",
      "Đồng Tiến",
      "Hồi Xuân",
      "Nam Xuân",
      "Thiên Phủ",
      "Hiền Kiệt",
      "Phú Lệ",
      "Trung Thành",
      "Trung Hạ",
      "Linh Sơn",
      "Đồng Lương",
      "Văn Phú",
      "Giao An",
      "Bá Thước",
      "Thiết Ống",
      "Văn Nho",
      "Điền Quang",
      "Điền Lư",
      "Quý Lương",
      "Cổ Lũng",
      "Pù Luông",
      "Ngọc Lặc",
      "Thạch Lập",
      "Ngọc Liên",
      "Minh Sơn",
      "Nguyệt Ấn",
      "Kiên Thọ",
      "Cẩm Thạch",
      "Cẩm Thủy",
      "Cẩm Tú",
      "Cẩm Vân",
      "Cẩm Tân",
      "Kim Tân",
      "Vân Du",
      "Ngọc Trạo",
      "Thạch Bình",
      "Thành Vinh",
      "Thạch Quảng",
      "Như Xuân",
      "Thượng Ninh",
      "Hóa Quỳ",
      "Xuân Bình",
      "Thanh Phong",
      "Thanh Quân",
      "Xuân Du",
      "Mậu Lâm",
      "Thường Xuân",
      "Thắng Lộc",
      "Xuân Chinh",
      "Hạc Thành",
      "Hà Trung",
      "Thiệu Hóa",
      "Quan Sơn",
      "Như Thanh"
    ]
  },
  {
    "name": "Tuyên Quang",
    "wards": [
      "Ngọc Long",
      "Đồng Văn",
      "Minh Sơn",
      "Giáp Trung",
      "Hà Giang 2",
      "Ngọc Đường",
      "Tiên Nguyên",
      "Vị Xuyên",
      "Cao Bồ",
      "Mèo Vạc",
      "Thuận Hòa",
      "Thượng Sơn",
      "Tùng Bá",
      "Việt Lâm",
      "Quảng Nguyên",
      "Minh Ngọc",
      "Hà Giang 1",
      "Minh Tân",
      "Nông Tiến",
      "Minh Xuân",
      "Trung Hà",
      "Hùng Đức",
      "Kiến Thiết",
      "Mỹ Lâm",
      "Tân Tiến",
      "Hoàng Su Phì",
      "Thàng Tín",
      "Bản Máy",
      "Pờ Ly Ngài",
      "Xín Mần",
      "Pà Vầy Sủ",
      "Nấm Dẩn",
      "Trung Thịnh",
      "Khuôn Lùng",
      "Lũng Cú",
      "Sà Phìn",
      "Phố Bảng",
      "Lũng Phìn",
      "Sủng Máng",
      "Sơn Vĩ",
      "Khâu Vai",
      "Niêm Sơn",
      "Tát Ngà",
      "Thắng Mố",
      "Bạch Đích",
      "Yên Minh",
      "Mậu Duệ",
      "Du Già",
      "Đường Thượng",
      "Lùng Tám",
      "Cán Tỷ",
      "Nghĩa Thuận",
      "Quản Bạ",
      "Tùng Vài",
      "Yên Cường",
      "Đường Hồng",
      "Bắc Mê",
      "Lao Chải",
      "Thanh Thủy",
      "Phú Linh",
      "Linh Hồ",
      "Bạch Ngọc",
      "Tân Quang",
      "Đồng Tâm",
      "Liên Hiệp",
      "Bằng Hành",
      "Bắc Quang",
      "Hùng An",
      "Vĩnh Tuy",
      "Đồng Yên",
      "Tiên Yên",
      "Xuân Giang",
      "Bằng Lang",
      "Yên Thành",
      "Quang Bình",
      "Tân Trịnh",
      "Thông Nguyên",
      "Hồ Thầu",
      "Nậm Dịch",
      "Thái Bình",
      "Thượng Lâm",
      "Lâm Bình",
      "Minh Quang",
      "Bình An",
      "Côn Lôn",
      "Yên Hoa",
      "Thượng Nông",
      "Hồng Thái",
      "Nà Hang",
      "Tân Mỹ",
      "Yên Lập",
      "Tân An",
      "Chiêm Hoá",
      "Hoà An",
      "Kiên Đài",
      "Tri Phú",
      "Kim Bình",
      "Yên Nguyên",
      "Yên Phú",
      "Bạch Xa",
      "Phù Lưu",
      "Hàm Yên",
      "Bình Xa",
      "Thái Sơn",
      "Thái Hoà",
      "Hùng Lợi",
      "Trung Sơn",
      "Tân Long",
      "Xuân Vân",
      "Lực Hành",
      "Yên Sơn",
      "Nhữ Khê",
      "Tân Trào",
      "Minh Thanh",
      "Sơn Dương",
      "Bình Ca",
      "Tân Thanh",
      "Sơn Thuỷ",
      "Phú Lương",
      "Trường Sinh",
      "Hồng Sơn",
      "Đông Thọ",
      "An Tường",
      "Bình Thuận"
    ]
  },
  {
    "name": "Vĩnh Long",
    "wards": [
      "Hòa Minh",
      "Long Hòa",
      "Đông Hải",
      "Long Hữu",
      "Long Vĩnh",
      "Cái Vồn",
      "Bình Minh",
      "Tam Bình",
      "Ngãi Tứ",
      "Trà Ôn",
      "Trà Côn",
      "Cái Nhum",
      "Tân Long Hội",
      "Nhơn Phú",
      "Bình Phước",
      "An Bình",
      "Long Hồ",
      "Phú Quới",
      "Thanh Đức",
      "Long Châu",
      "Phước Hậu",
      "Tân Hạnh",
      "Tân Ngãi",
      "Quới Thiện",
      "Trung Thành",
      "Trung Ngãi",
      "Quới An",
      "Trung Hiệp",
      "Hiếu Phụng",
      "Hiếu Thành",
      "Lục Sỹ Thành",
      "Vĩnh Xuân",
      "Hòa Bình",
      "Hòa Hiệp",
      "Song Phú",
      "Cái Ngang",
      "Tân Quới",
      "Tân Lược",
      "Mỹ Thuận",
      "Đông Thành",
      "Trà Vinh",
      "Long Đức",
      "Nguyệt Hóa",
      "Hòa Thuận",
      "Càng Long",
      "An Trường",
      "Tân An",
      "Nhị Long",
      "Bình Phú",
      "Châu Thành",
      "Song Lộc",
      "Hưng Mỹ",
      "Cầu Kè",
      "Phong Thạnh",
      "An Phú Tân",
      "Tam Ngãi",
      "Tiểu Cần",
      "Tân Hòa",
      "Hùng Hòa",
      "Tập Ngãi",
      "Cầu Ngang",
      "Mỹ Long",
      "Vinh Kim",
      "Nhị Trường",
      "Hiệp Mỹ",
      "Trà Cú",
      "Đại An",
      "Lưu Nghiệp Anh",
      "Hàm Giang",
      "Long Hiệp",
      "Tập Sơn",
      "Duyên Hải",
      "Trường Long Hòa",
      "Long Thành",
      "Đôn Châu",
      "Ngũ Lạc",
      "An Hội",
      "Phú Khương",
      "Bến Tre",
      "Sơn Đông",
      "Phú Tân",
      "Phú Túc",
      "Giao Long",
      "Tiên Thủy",
      "Tân Phú",
      "Phú Phụng",
      "Chợ Lách",
      "Vĩnh Thành",
      "Hưng Khánh Trung",
      "Phước Mỹ Trung",
      "Tân Thành Bình",
      "Nhuận Phú Tân",
      "Đồng Khởi",
      "Mỏ Cày",
      "Thành Thới",
      "An Định",
      "Hương Mỹ",
      "Đại Điền",
      "Quới Điền",
      "Thạnh Phú",
      "An Qui",
      "Thạnh Hải",
      "Thạnh Phong",
      "Tân Thủy",
      "Bảo Thạnh",
      "Ba Tri",
      "Tân Xuân",
      "Mỹ Chánh Hòa",
      "An Ngãi Trung",
      "An Hiệp",
      "Hưng Nhượng",
      "Giồng Trôm",
      "Tân Hào",
      "Phước Long",
      "Lương Phú",
      "Châu Hòa",
      "Lương Hòa",
      "Thới Thuận",
      "Thạnh Phước",
      "Bình Đại",
      "Thạnh Trị",
      "Lộc Thuận",
      "Châu Hưng",
      "Phú Thuận"
    ]
  }
];